### ISSUE TITLE
Is there a way to handle illegal file name characters on unpacking .tar.gz files?

### ISSUE THREAD

**Issue by paul42** [icsharpcode/SharpZipLib#220]
### Steps to reproduce
1. on linux machine, create .tar.gz archive where one or more files have `:` in the name
2. on windows 2012r2 machine with this library, follow the standard example in docs for extracting to destination folder
3. get error: `The given path's format is not supported.`

### Expected behavior
Notify user of failing file name (I don't think I see it in my stack trace) or allow user to submit a function/delegate for reading file names and to handle bad characters before they throw an exception

### Actual behavior
Get Exception: 
````
The given path's format is not supported.
System.NotSupportedException
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractEntry(String destDir, TarEntry entry)
   at ICSharpCode.SharpZipLib.Tar.TarArchive.ExtractContents(String destinationDirectory)
````

### Version of SharpZipLib
looking in my packages.config:
` <package id="SharpZipLib" version="0.86.0" targetFramework="net461" />`

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

Really love the library, and I'm sure there's a fix in there somewhere but I don't knwo where to find it due to the documentation - if you have a second to point me in the right direction, or even give me an entry point where I can start exploring I could possibly try for a Pull Request with fix, but I'm still a bit of a novice

Either way, thanks for your time!
-Paul42

**Comment by paul42** [comment]
looks like I just need to use a different method instead of the convenience method that does it all for you.

https://github.com/icsharpcode/SharpZipLib/wiki/GZip-and-Tar-Samples#extractFull
