### ISSUE TITLE
Disparity between versions

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#24]
[SD-332](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=332), originally created on 2/20/2005 11:51:18 by John Reilly

Seems to be a disparity between versions and what can be compressed
/decompressed.

We are using a prior version of SharpZipLib and recently noticed a
problem when compressing very large data - after the data was compressed
it could not be uncompressed without an exception being thrown. We
upgraded to the most recent version which corrected that problem, but,
it introduced a more serious problem. We could not uncompress ANY of the
data that had been compressed with the prior version - we save
compressed data in a database for retrieval at a later time.

The exception we get is:

"BZip2 input stream bad block header"

ICSharpCode.SharpZipLib.BZip2.BZip2InputStream.BadBlockHeader()

at ICSharpCode.SharpZipLib.BZip2.BZip2InputStream.InitBlock()

at ICSharpCode.SharpZipLib.BZip2.BZip2InputStream..ctor(Stream stream)

We can use the same code and switch back to the previous version of
SharpZipLib and then we are able to successfully uncompress the data
that was compressed with that same prior version. It seems like
SharpZipLib will only uncompress data that was compressed with the same
version. Is this correct?

Here is the code where the Exception is thrown.

public static byte[] DecompressToBytes(byte[] bytesToDecompress)

{

byte[] writeData = new byte[4096];

Stream inStream = null;

MemoryStream outStream = new MemoryStream();

try

{

--->>>> inStream = new BZip2InputStream(new
MemoryStream(bytesToDecompress));

}

catch(Exception e)

{

throw e;

}

 

 
## 

-- Brian Shepler

-- brian@moretechnologies.com
##

**Comment by piksel** [comment]
Closing this due to inactivity and age.
