### ISSUE TITLE
InflaterInputStream throws 'Invalid input data' when unpacking certain files using RC1

### ISSUE THREAD

**Issue by DmitriyKirakosyan** [icsharpcode/SharpZipLib#253]
### Steps to reproduce
1. Get zip with `.jar` file inside
2. Unpack it using FastZip or https://github.com/icsharpcode/SharpZipLib/wiki/Zip-Samples
3. Observe the exception:
```
ICSharpCode.SharpZipLib.Zip.ZipException: Invalid input data
  at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00064] in <c593097fc4b94ac1b244b4fb8b18cca4>:0 
  at ICSharpCode.SharpZipLib.Core.StreamUtils.Copy (System.IO.Stream source, System.IO.Stream destination, System.Byte[] buffer) [0x00048] in <c593097fc4b94ac1b244b4fb8b18cca4>:0 
```

### Expected behavior
Should successfully unzip an archive.

### Actual behavior
Throws exception when unzipping `.jar` file

### Version of SharpZipLib
1.0.0-rc1

### Obtained from (place an x between the brackets for all that apply)
- [ ] Compiled from source
 - branch: _______
 - commit: _______
- [ ] Downloaded DLL from GitHub
- [ ] Downloaded DLL from SourceForge
- [ ] Downloaded DLL from _______
- [ ] DLL included as part of
- Package installed using:
 - [x] NuGet
 - [ ] MyGet
 - [ ] Chocolatey

**Comment by piksel** [comment]
I am not able to reproduce the error, could you show your code and upload the problematic file?
You can upload it by dragging it to the textbox.

Test sample created using:
```
echo "content" > test.txt
jar cf test.jar test.txt
7z a test.zip test.jar
```
Running simple repro project:
https://gist.github.com/piksel/426a492933a2421bfd10d40f2b2f0335
```
D:\tmp> dotnet run -- test.zip
Extracting contents of test.zip to out...

D:\tmp> dir out
Directory: D:\tmp\out
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2018-07-18     20:26            459 test.jar
```

**Comment by johnfedak** [comment]
I had to back out the RC due what I think is the same issue.  
The files that were failing were gziped text files.

**Comment by piksel** [comment]
@johnfedak Could you try and see if this fixes the issue?
https://ci.appveyor.com/api/buildjobs/8rq1q4ls493q2fk0/artifacts/SharpZipLib.1.0.0-git0e70f00.nupkg

**Comment by johnfedak** [comment]
Yes, that appears to have addressed the issue.  Thanks.

**Comment by DmitriyKirakosyan** [comment]
@piksel Just realised that not all jars cause the issue. To reproduce it you can simply take this google's [zip file](https://dl.google.com/android/repository/android-22_r02.zip).
Sorry that I didn't test it on a simple jar file.

I've tested the package from https://github.com/icsharpcode/SharpZipLib/issues/253#issuecomment-406045001, and indeed it seems working to me.

Would be nice to see it in master and the NuGet updated 🤩

**Comment by 263613093** [comment]
SharpZipLib  version 1.0.0-rc-1

unpacking zip file throw exception

StackTrace as:
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.BodyRead(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.InitialRead(Byte[] destination, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ConsoleAppTest.Utility.ZipHelper.ChangePackage(String zipSource, String sourcePassword, String destZip, String destPassword, IEnumerable`1 newFiles, IEnumerable`1 delFiles) in D:\Others\Demo\ConsoleAppTest\Utility\ZipHelper.cs:line 84
   at.....

when i uninstall this version and then install v0.86.0
it can unpacking zip file success!

**Comment by piksel** [comment]
@263613093, yes this does indeed seem to be the same bug. I will be releasing RC2 shortly with the fix.
