### ISSUE TITLE
Entry closed at '0' before the '15' bytes specified in the header were written

### ISSUE THREAD

**Issue by trampster** [icsharpcode/SharpZipLib#651]
I'm trying to write to create a tar.gz in Blazor completely in memory.

Below is my code. You can see that I create a TarEntry sets it's size then write it to the tar.

```
using (var outStream = new MemoryStream())
using (var gzoStream = new GZipOutputStream(outStream))
using (var tar = new TarOutputStream(gzoStream, Encoding.ASCII))
using (var tarArchive = TarArchive.CreateOutputTarArchive(tar))
{
    tarArchive.RootPath = "MyFolder";
    var fileContents = Encoding.UTF8.GetBytes("This is my file");
    var tarEntry = TarEntry.CreateTarEntry("MyFile.txt");
    tarEntry.Size = fileContents.Length;
    tar.PutNextEntry(tarEntry);
    tar.Write(fileContents, 0, fileContents.Length);
    tar.CloseEntry();
    tarArchive.WriteEntry(tarEntry,true);
    tar.Close();
    outStream.Position = 0;
    return outStream.ToArray();
}
```

However after creating my TarEntry and trying to write it I get the following error:

```
Unhandled exception rendering component: Entry closed at '0' before the '15' bytes specified in the header were written
      ICSharpCode.SharpZipLib.Tar.TarException: Entry closed at '0' before the '15' bytes specified in the header were written
         at ICSharpCode.SharpZipLib.Tar.TarOutputStream.CloseEntry()
         at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Finish()
         at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Dispose(Boolean disposing)
         at System.IO.Stream.Close()
         at System.IO.Stream.Dispose()
         at ICSharpCode.SharpZipLib.Tar.TarArchive.Dispose(Boolean disposing)
         at ICSharpCode.SharpZipLib.Tar.TarArchive.Dispose()
         at BlazorConfig.Data.UsersService.CreateTarGZ() in /home/daniel/Work/BlazorConfig/BlazorConfig/Data/UsersService.cs:line 73
         at BlazorConfig.Pages.Users.DownloadBinary() in /home/daniel/Work/BlazorConfig/BlazorConfig/Pages/Users.razor:line 57
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
```

As can be seen in my code I have written the file contents to the tar, but for some reason it doesn't think I have.

**Comment by trampster** [comment]
I needed to remove tar.CloseEntry();
