### ISSUE TITLE
ObjectDisposedException at BZip2OutputStream.Finalize()

### ISSUE THREAD

**Issue by tdhintz** [icsharpcode/SharpZipLib#68]
Uncontrolled cleanup of lost IIS sessions causes a crash.  Finalize should not throw.

Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
Stack:
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Write(Byte[], Int32, Int32)
   at System.Security.Cryptography.CryptoStream.Write(Byte[], Int32, Int32)
   at System.IO.Stream.WriteByte(Byte)
   at ICSharpCode.SharpZipLib.BZip2.BZip2OutputStream.BsW(Int32, Int32)
   at ICSharpCode.SharpZipLib.BZip2.BZip2OutputStream.BsPutint(Int32)
   at ICSharpCode.SharpZipLib.BZip2.BZip2OutputStream.EndBlock()
   at ICSharpCode.SharpZipLib.BZip2.BZip2OutputStream.Dispose(Boolean)
   at ICSharpCode.SharpZipLib.BZip2.BZip2OutputStream.Finalize()

**Comment by McNeight** [comment]
Fixed with pull request #69 

-Neil
