### ISSUE TITLE
Async entry read causes exception when reading AES encrypted zip.

### ISSUE THREAD

**Issue by rilehudd** [icsharpcode/SharpZipLib#823]
### Describe the bug

When trying to read an encrypted archive's entry's input stream asynchronously, it reports an exception containing message: "Auth code missing from input stream".

Yet, if the same archive is read synchronously it works fine.

### Reproduction Code

https://dotnetfiddle.net/RhJM7o

### Steps to reproduce

It doesn't seem to happen for every input. But for inputs where it does happen, changing the async call to the synchronous version fixes the problem.

The zip input is in the dotnetfiddle.

The steps to create the zip archive from 7-Zip are:
1. Using the file provided (appendix A)
2. 7-Zip -> Add to archive
3. Ensure params:
- Archive Format: Zip
- Compression level: 5 - Normal
- Compression method: * Deflate
- Encryption method: AES-256
- Set password (I set mine to "test")

4. Run the decompress/decrypt steps outlined in the [dotnetfiddle](https://dotnetfiddle.net/RhJM7o)

### Expected behavior

For the same input, I expected them both to work (the synchronous and the asynchronous).

### Operating System

Windows

### Framework Version

.NET 6

### Tags

ZIP, Encryption, Async

**Comment by piksel** [comment]
Thanks for the report and for actually using the dotnet fiddle template!
I compacted it somewhat to emphasise that the only difference is the async/sync calls: https://dotnetfiddle.net/5alzjK

I have not found I cause yet, but I will look into this as soon I can.

**Comment by piksel** [comment]
Yeah, this is yet another time that the framework bypasses the public methods of `CryptoStream` for increased performance.
`ZipAESStream` overrides the `Read` and `ReadAsync` methods of `CryptoStream`, but as you can see from the

<details>
<summary>Stacktrace</summary>

```
   at ICSharpCode.SharpZipLib.Encryption.ZipAESTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount) in /_/src/ICSharpCode.SharpZipLib/Encryption/ZipAESTransform.cs:line 141
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Program.<<Main>$>g__Repro|0_0(String type)
   at Program.<<Main>$>g__TestAsync|0_2[T](Func`2 a, T input)
```

</details>

, `StreamReader` just bypasses `ReadAsync` and calls `ReadAsyncCore` directly, which bypasses our read logic. That method is internal and cannot be override by us.

**Comment by piksel** [comment]
As for consumers (including @rilehudd), you can replace the `StreamReader` with:
```cs
var e2 = zip.GetEntry("abcdefgh.txt");
var entryStream = zip.GetInputStream(e2);
var entryBuffer = new byte[e2.Size];
using (var ms2 = new MemoryStream(entryBuffer))
{
	byte[] buffer = new byte[ushort.MaxValue];
  	int read;

	if (type == "async") 
    {

		while ((read = await entryStream.ReadAsync(buffer, 0, buffer.Length)) > 0)
		{
			ms2.Write(buffer, 0, read);
		}

	} 
    else 
    {
		while ((read = entryStream.Read(buffer, 0, buffer.Length)) > 0)
		{
			ms2.Write(buffer, 0, read);
		}
	}
	var output = Encoding.UTF8.GetString(entryBuffer);

      // ... use output ...
}

```

It's not ideal, for sure, but that is the only async path that avoids the optimisations in .NET that bypasses the AES encryption logic.

**Comment by rilehudd** [comment]
Is there a way we can detect this "bypassed" state an compensate for this optimization?
For example detect that ZipAESTransform.TransformFinalBlock has been called from the non-expected path (to implement what CryptoStream is expecting). I'm may not be understanding the feasibility of attempting to compensate for the optimization. Or maybe it is possible but would result in unacceptable complexity. (I wonder what dotnet designers expected implementors to do with them bypassing public methods).

Otherwise, it seems like this might be an optimization that might likely affect many encryption stream implementations. Do you think it makes sense to submit this optimization bug upstream to dotnet?

**Comment by rilehudd** [comment]
Thanks for taking the time to take a look at this!

**Comment by piksel** [comment]
There *is* another solution to this. The compression method that is used for the entry is STORE, which means that it's uncompressed. This problem only happens to such entries because we directly return the `ZipAESStream` to the consumer. If there is some decompression to be done, the stream will be wrapped in the appropriate decompression stream, and the optimized path is not taken. We could add a `StoreOutputStream` that just passes the data through, but in doing so mitigates this problem.
